doctrine_migrations:
    migrations_paths:
        'App\Blog\Infrastructure\Migrations': '%kernel.project_dir%/src/Blog/Infrastructure/Migrations'

    storage:
        table_storage:
            table_name: 'doctrine_migration_versions'
            version_column_name: 'version'
            version_column_length: 191
            executed_at_column_name: 'executed_at'
