parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

            - '../src/*/Domain/Entity/'
            - '../src/*/Domain/ValueObject/'
            - '../src/*/Domain/Event/'

            - '../src/*/Application/DTO/'
            - '../src/*/Application/UseCase/**/*Command.php'
            - '../src/*/Application/UseCase/**/*Query.php'

    App\Blog\Infrastructure\Http\:
        resource: '../src/Blog/Infrastructure/Http/**/*Controller.php'
        tags: [ 'controller.service_arguments' ]


    App\Common\Infrastructure\Events\DomainExceptionSubscriber:
        arguments:
            $environment: '%kernel.environment%'
        tags: ['kernel.event_subscriber']
